// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./../src/components/Card.vue')['default']
    Cobe: typeof import('./../src/components/Cobe.vue')['default']
    Decorator: typeof import('./../src/components/Decorator.vue')['default']
    DigitalClock: typeof import('./../src/components/DigitalClock.vue')['default']
    Fullscreen: typeof import('./../src/components/Fullscreen.vue')['default']
    IconCustomFullscreen: typeof import('~icons/custom/fullscreen')['default']
    IconCustomFullscreenExit: typeof import('~icons/custom/fullscreen-exit')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
