// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./../src/components/Card.vue')['default']
    Cobe: typeof import('./../src/components/Cobe.vue')['default']
    Decorator: typeof import('./../src/components/Decorator.vue')['default']
    DigitalClock: typeof import('./../src/components/DigitalClock.vue')['default']
    Fullscreen: typeof import('./../src/components/Fullscreen.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    Modal: typeof import('./../src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBoard: typeof import('./../src/components/ScrollBoard.vue')['default']
  }
}
