// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./../components/Card.vue')['default']
    ClockDigital: typeof import('./../components/Clock/Digital.vue')['default']
    Cobe: typeof import('./../components/Cobe.vue')['default']
    Decorator: typeof import('./../components/Decorator.vue')['default']
    FullscreenToggle: typeof import('./../components/FullscreenToggle.vue')['default']
    IconCustomFullscreen: typeof import('~icons/custom/fullscreen')['default']
    IconCustomFullscreenExit: typeof import('~icons/custom/fullscreen-exit')['default']
  }
}

export { }
